baseURL = 'https://vosai.live/'
languageCode = 'en-us'
title = 'VoSai Collective'
theme = 'ananke'

[params]
  description = 'Transmissions from the Northern Wilderness'
  author = 'The VoSai Collective'
  background_color_class = 'bg-black'
  text_color = 'white'
  featured_image = ''
  recent_posts_number = 5
